[package]
name = "priority-queue"
version = "0.1.0"
authors = ["william-bishop <admin@the402.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
